server:
  port: 8080

app:
  third-party-app-frontend-base-url: http://127.0.0.1:5173
  resource-app-frontend-base-url: http://127.0.0.1:5174

okta:
  issuer: ${OKTA_ISSUER:https://integrator-7968552.okta.com/oauth2/default}
  client-id: ${OKTA_CLIENT_ID:0oa13uf5a4lJCV4Pi698}
  client-secret: ${OKTA_CLIENT_SECRET:UlyfHj9nsO2-W8XxuYaLv7MJOdbjrjKtWF5G9nhY7Uu7NcBHXQC2q-yUhbEMEUi0}
  redirect-uri: ${OKTA_REDIRECT_URI:http://127.0.0.1:8080/login/callback}
